services:
  frontend:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - .:/usr/share/nginx/html/:ro
    depends_on:
      - backend
      - whisper
    environment:
      - BACKEND_URL=http://backend:8000
      - WHISPER_URL=ws://whisper:9000
    networks:
      - ar-gen-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend/models:/app/models
      - ./backend/app:/app/app
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    networks:
      - ar-gen-network

  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ./whisper:/app
    environment:
      - WHISPER_MODEL=base
      - WHISPER_DEVICE=auto
      - WHISPER_HOST=0.0.0.0
      - WHISPER_PORT=9000
    networks:
      - ar-gen-network

networks:
  ar-gen-network:
    driver: bridge
