version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - rivendell-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
      - ./backend/app:/app/app
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    networks:
      - rivendell-network

networks:
  rivendell-network:
    driver: bridge
