services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - whisper
    environment:
      - BACKEND_URL=http://backend:8000
      - WHISPER_URL=ws://whisper:9000
    networks:
      - ar-gen-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Use expose for internal-only; swap back to "ports" if you need host access.
    expose:
      - "8000"
    restart: always
    volumes:
      - ./backend/models:/app/models
      - ./backend/app:/app/app
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    networks:
      - ar-gen-network

  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    expose:
      - "9000"
    restart: always
    volumes:
      - ./whisper:/app
    environment:
      - WHISPER_MODEL=base
      - WHISPER_DEVICE=auto
      - WHISPER_HOST=0.0.0.0
      - WHISPER_PORT=9000
    networks:
      - ar-gen-network

volumes:
  caddy_data:
  caddy_config:

networks:
  ar-gen-network:
    driver: bridge
