version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # keep exposing frontend on host:3000
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - whisper
    environment:
      - BACKEND_URL=http://backend:8000
      - WHISPER_URL=ws://whisper:9000
    networks:
      - rivendell-network

  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80" # tiny reverse proxy on host:80 -> frontend
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - rivendell-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
      - ./backend/app:/app/app
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    networks:
      - rivendell-network

  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./whisper:/app
    environment:
      - WHISPER_MODEL=base
      - WHISPER_DEVICE=auto
      - WHISPER_HOST=0.0.0.0
      - WHISPER_PORT=9000
    networks:
      - rivendell-network

networks:
  rivendell-network:
    driver: bridge
